/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrutinizersReportRouteImport } from './routes/scrutinizers-report'
import { Route as IndexRouteImport } from './routes/index'

const ScrutinizersReportRoute = ScrutinizersReportRouteImport.update({
  id: '/scrutinizers-report',
  path: '/scrutinizers-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scrutinizers-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scrutinizers-report'
  id: '__root__' | '/' | '/scrutinizers-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScrutinizersReportRoute: typeof ScrutinizersReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrutinizers-report': {
      id: '/scrutinizers-report'
      path: '/scrutinizers-report'
      fullPath: '/scrutinizers-report'
      preLoaderRoute: typeof ScrutinizersReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScrutinizersReportRoute: ScrutinizersReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
