/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareTransferAgentRouteImport } from './routes/share-transfer-agent'
import { Route as ScrutinizersReportRouteImport } from './routes/scrutinizers-report'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as KeyManagementPersonnelRouteImport } from './routes/key-management-personnel'
import { Route as FinancialResultsRouteImport } from './routes/financial-results'
import { Route as ComplianceOfficerRouteImport } from './routes/compliance-officer'
import { Route as BoardOfDirectorsRouteImport } from './routes/board-of-directors'
import { Route as BoardMeetingsNoticesRouteImport } from './routes/board-meetings-notices'
import { Route as AgmNoticesRouteImport } from './routes/agm-notices'
import { Route as IndexRouteImport } from './routes/index'

const ShareTransferAgentRoute = ShareTransferAgentRouteImport.update({
  id: '/share-transfer-agent',
  path: '/share-transfer-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrutinizersReportRoute = ScrutinizersReportRouteImport.update({
  id: '/scrutinizers-report',
  path: '/scrutinizers-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyManagementPersonnelRoute = KeyManagementPersonnelRouteImport.update({
  id: '/key-management-personnel',
  path: '/key-management-personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialResultsRoute = FinancialResultsRouteImport.update({
  id: '/financial-results',
  path: '/financial-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceOfficerRoute = ComplianceOfficerRouteImport.update({
  id: '/compliance-officer',
  path: '/compliance-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOfDirectorsRoute = BoardOfDirectorsRouteImport.update({
  id: '/board-of-directors',
  path: '/board-of-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardMeetingsNoticesRoute = BoardMeetingsNoticesRouteImport.update({
  id: '/board-meetings-notices',
  path: '/board-meetings-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AgmNoticesRoute = AgmNoticesRouteImport.update({
  id: '/agm-notices',
  path: '/agm-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/financial-results': typeof FinancialResultsRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/policies': typeof PoliciesRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/financial-results': typeof FinancialResultsRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/policies': typeof PoliciesRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/financial-results': typeof FinancialResultsRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/policies': typeof PoliciesRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agm-notices'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/financial-results'
    | '/key-management-personnel'
    | '/policies'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agm-notices'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/financial-results'
    | '/key-management-personnel'
    | '/policies'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
  id:
    | '__root__'
    | '/'
    | '/agm-notices'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/financial-results'
    | '/key-management-personnel'
    | '/policies'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgmNoticesRoute: typeof AgmNoticesRoute
  BoardMeetingsNoticesRoute: typeof BoardMeetingsNoticesRoute
  BoardOfDirectorsRoute: typeof BoardOfDirectorsRoute
  ComplianceOfficerRoute: typeof ComplianceOfficerRoute
  FinancialResultsRoute: typeof FinancialResultsRoute
  KeyManagementPersonnelRoute: typeof KeyManagementPersonnelRoute
  PoliciesRoute: typeof PoliciesRoute
  ScrutinizersReportRoute: typeof ScrutinizersReportRoute
  ShareTransferAgentRoute: typeof ShareTransferAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-transfer-agent': {
      id: '/share-transfer-agent'
      path: '/share-transfer-agent'
      fullPath: '/share-transfer-agent'
      preLoaderRoute: typeof ShareTransferAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrutinizers-report': {
      id: '/scrutinizers-report'
      path: '/scrutinizers-report'
      fullPath: '/scrutinizers-report'
      preLoaderRoute: typeof ScrutinizersReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-management-personnel': {
      id: '/key-management-personnel'
      path: '/key-management-personnel'
      fullPath: '/key-management-personnel'
      preLoaderRoute: typeof KeyManagementPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-results': {
      id: '/financial-results'
      path: '/financial-results'
      fullPath: '/financial-results'
      preLoaderRoute: typeof FinancialResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-officer': {
      id: '/compliance-officer'
      path: '/compliance-officer'
      fullPath: '/compliance-officer'
      preLoaderRoute: typeof ComplianceOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-of-directors': {
      id: '/board-of-directors'
      path: '/board-of-directors'
      fullPath: '/board-of-directors'
      preLoaderRoute: typeof BoardOfDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-meetings-notices': {
      id: '/board-meetings-notices'
      path: '/board-meetings-notices'
      fullPath: '/board-meetings-notices'
      preLoaderRoute: typeof BoardMeetingsNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agm-notices': {
      id: '/agm-notices'
      path: '/agm-notices'
      fullPath: '/agm-notices'
      preLoaderRoute: typeof AgmNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgmNoticesRoute: AgmNoticesRoute,
  BoardMeetingsNoticesRoute: BoardMeetingsNoticesRoute,
  BoardOfDirectorsRoute: BoardOfDirectorsRoute,
  ComplianceOfficerRoute: ComplianceOfficerRoute,
  FinancialResultsRoute: FinancialResultsRoute,
  KeyManagementPersonnelRoute: KeyManagementPersonnelRoute,
  PoliciesRoute: PoliciesRoute,
  ScrutinizersReportRoute: ScrutinizersReportRoute,
  ShareTransferAgentRoute: ShareTransferAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
