/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareholdingPatternSept2016RouteImport } from './routes/shareholding-pattern-sept-2016'
import { Route as ShareholdingPatternSep2025RouteImport } from './routes/shareholding-pattern-sep-2025'
import { Route as ShareholdingPatternSep2023RouteImport } from './routes/shareholding-pattern-sep-2023'
import { Route as ShareholdingPatternSep2022RouteImport } from './routes/shareholding-pattern-sep-2022'
import { Route as ShareholdingPatternSep2021RouteImport } from './routes/shareholding-pattern-sep-2021'
import { Route as ShareholdingPatternSep2020RouteImport } from './routes/shareholding-pattern-sep-2020'
import { Route as ShareholdingPatternMarch2017RouteImport } from './routes/shareholding-pattern-march-2017'
import { Route as ShareholdingPatternMar2026RouteImport } from './routes/shareholding-pattern-mar-2026'
import { Route as ShareholdingPatternMar2025RouteImport } from './routes/shareholding-pattern-mar-2025'
import { Route as ShareholdingPatternMar2023RouteImport } from './routes/shareholding-pattern-mar-2023'
import { Route as ShareholdingPatternMar2022RouteImport } from './routes/shareholding-pattern-mar-2022'
import { Route as ShareholdingPatternMar2021RouteImport } from './routes/shareholding-pattern-mar-2021'
import { Route as ShareholdingPatternJune2025RouteImport } from './routes/shareholding-pattern-june-2025'
import { Route as ShareholdingPatternJune2024RouteImport } from './routes/shareholding-pattern-june-2024'
import { Route as ShareholdingPatternJune2023RouteImport } from './routes/shareholding-pattern-june-2023'
import { Route as ShareholdingPatternJune2021RouteImport } from './routes/shareholding-pattern-june-2021'
import { Route as ShareholdingPatternDec2025RouteImport } from './routes/shareholding-pattern-dec-2025'
import { Route as ShareholdingPatternDec2024RouteImport } from './routes/shareholding-pattern-dec-2024'
import { Route as ShareholdingPatternDec2022RouteImport } from './routes/shareholding-pattern-dec-2022'
import { Route as ShareholdingPatternDec2021RouteImport } from './routes/shareholding-pattern-dec-2021'
import { Route as ShareholdingPatternDec2020RouteImport } from './routes/shareholding-pattern-dec-2020'
import { Route as ShareholdingPatternDec2016RouteImport } from './routes/shareholding-pattern-dec-2016'
import { Route as ShareholdingPatternRouteImport } from './routes/shareholding-pattern'
import { Route as ShareTransferAgentRouteImport } from './routes/share-transfer-agent'
import { Route as ScrutinizersReportRouteImport } from './routes/scrutinizers-report'
import { Route as RscaReportsRouteImport } from './routes/rsca-reports'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as NewspaperPublicationsRouteImport } from './routes/newspaper-publications'
import { Route as KeyManagementPersonnelRouteImport } from './routes/key-management-personnel'
import { Route as InvestorGrievanceRouteImport } from './routes/investor-grievance'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FinancialResultsRouteImport } from './routes/financial-results'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceOfficerRouteImport } from './routes/compliance-officer'
import { Route as BoardOfDirectorsRouteImport } from './routes/board-of-directors'
import { Route as BoardMeetingsNoticesRouteImport } from './routes/board-meetings-notices'
import { Route as AnnualReturnsRouteImport } from './routes/annual-returns'
import { Route as AnnualReportsRouteImport } from './routes/annual-reports'
import { Route as AgmResultsRouteImport } from './routes/agm-results'
import { Route as AgmNoticesRouteImport } from './routes/agm-notices'
import { Route as IndexRouteImport } from './routes/index'

const ShareholdingPatternSept2016Route =
  ShareholdingPatternSept2016RouteImport.update({
    id: '/shareholding-pattern-sept-2016',
    path: '/shareholding-pattern-sept-2016',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternSep2025Route =
  ShareholdingPatternSep2025RouteImport.update({
    id: '/shareholding-pattern-sep-2025',
    path: '/shareholding-pattern-sep-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternSep2023Route =
  ShareholdingPatternSep2023RouteImport.update({
    id: '/shareholding-pattern-sep-2023',
    path: '/shareholding-pattern-sep-2023',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternSep2022Route =
  ShareholdingPatternSep2022RouteImport.update({
    id: '/shareholding-pattern-sep-2022',
    path: '/shareholding-pattern-sep-2022',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternSep2021Route =
  ShareholdingPatternSep2021RouteImport.update({
    id: '/shareholding-pattern-sep-2021',
    path: '/shareholding-pattern-sep-2021',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternSep2020Route =
  ShareholdingPatternSep2020RouteImport.update({
    id: '/shareholding-pattern-sep-2020',
    path: '/shareholding-pattern-sep-2020',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMarch2017Route =
  ShareholdingPatternMarch2017RouteImport.update({
    id: '/shareholding-pattern-march-2017',
    path: '/shareholding-pattern-march-2017',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMar2026Route =
  ShareholdingPatternMar2026RouteImport.update({
    id: '/shareholding-pattern-mar-2026',
    path: '/shareholding-pattern-mar-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMar2025Route =
  ShareholdingPatternMar2025RouteImport.update({
    id: '/shareholding-pattern-mar-2025',
    path: '/shareholding-pattern-mar-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMar2023Route =
  ShareholdingPatternMar2023RouteImport.update({
    id: '/shareholding-pattern-mar-2023',
    path: '/shareholding-pattern-mar-2023',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMar2022Route =
  ShareholdingPatternMar2022RouteImport.update({
    id: '/shareholding-pattern-mar-2022',
    path: '/shareholding-pattern-mar-2022',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternMar2021Route =
  ShareholdingPatternMar2021RouteImport.update({
    id: '/shareholding-pattern-mar-2021',
    path: '/shareholding-pattern-mar-2021',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternJune2025Route =
  ShareholdingPatternJune2025RouteImport.update({
    id: '/shareholding-pattern-june-2025',
    path: '/shareholding-pattern-june-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternJune2024Route =
  ShareholdingPatternJune2024RouteImport.update({
    id: '/shareholding-pattern-june-2024',
    path: '/shareholding-pattern-june-2024',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternJune2023Route =
  ShareholdingPatternJune2023RouteImport.update({
    id: '/shareholding-pattern-june-2023',
    path: '/shareholding-pattern-june-2023',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternJune2021Route =
  ShareholdingPatternJune2021RouteImport.update({
    id: '/shareholding-pattern-june-2021',
    path: '/shareholding-pattern-june-2021',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2025Route =
  ShareholdingPatternDec2025RouteImport.update({
    id: '/shareholding-pattern-dec-2025',
    path: '/shareholding-pattern-dec-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2024Route =
  ShareholdingPatternDec2024RouteImport.update({
    id: '/shareholding-pattern-dec-2024',
    path: '/shareholding-pattern-dec-2024',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2022Route =
  ShareholdingPatternDec2022RouteImport.update({
    id: '/shareholding-pattern-dec-2022',
    path: '/shareholding-pattern-dec-2022',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2021Route =
  ShareholdingPatternDec2021RouteImport.update({
    id: '/shareholding-pattern-dec-2021',
    path: '/shareholding-pattern-dec-2021',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2020Route =
  ShareholdingPatternDec2020RouteImport.update({
    id: '/shareholding-pattern-dec-2020',
    path: '/shareholding-pattern-dec-2020',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternDec2016Route =
  ShareholdingPatternDec2016RouteImport.update({
    id: '/shareholding-pattern-dec-2016',
    path: '/shareholding-pattern-dec-2016',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareholdingPatternRoute = ShareholdingPatternRouteImport.update({
  id: '/shareholding-pattern',
  path: '/shareholding-pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTransferAgentRoute = ShareTransferAgentRouteImport.update({
  id: '/share-transfer-agent',
  path: '/share-transfer-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrutinizersReportRoute = ScrutinizersReportRouteImport.update({
  id: '/scrutinizers-report',
  path: '/scrutinizers-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RscaReportsRoute = RscaReportsRouteImport.update({
  id: '/rsca-reports',
  path: '/rsca-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const NewspaperPublicationsRoute = NewspaperPublicationsRouteImport.update({
  id: '/newspaper-publications',
  path: '/newspaper-publications',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyManagementPersonnelRoute = KeyManagementPersonnelRouteImport.update({
  id: '/key-management-personnel',
  path: '/key-management-personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorGrievanceRoute = InvestorGrievanceRouteImport.update({
  id: '/investor-grievance',
  path: '/investor-grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialResultsRoute = FinancialResultsRouteImport.update({
  id: '/financial-results',
  path: '/financial-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceOfficerRoute = ComplianceOfficerRouteImport.update({
  id: '/compliance-officer',
  path: '/compliance-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOfDirectorsRoute = BoardOfDirectorsRouteImport.update({
  id: '/board-of-directors',
  path: '/board-of-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardMeetingsNoticesRoute = BoardMeetingsNoticesRouteImport.update({
  id: '/board-meetings-notices',
  path: '/board-meetings-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReturnsRoute = AnnualReturnsRouteImport.update({
  id: '/annual-returns',
  path: '/annual-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReportsRoute = AnnualReportsRouteImport.update({
  id: '/annual-reports',
  path: '/annual-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AgmResultsRoute = AgmResultsRouteImport.update({
  id: '/agm-results',
  path: '/agm-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AgmNoticesRoute = AgmNoticesRouteImport.update({
  id: '/agm-notices',
  path: '/agm-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/agm-results': typeof AgmResultsRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/annual-returns': typeof AnnualReturnsRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/contact': typeof ContactRoute
  '/financial-results': typeof FinancialResultsRoute
  '/forms': typeof FormsRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/newspaper-publications': typeof NewspaperPublicationsRoute
  '/policies': typeof PoliciesRoute
  '/rsca-reports': typeof RscaReportsRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
  '/shareholding-pattern': typeof ShareholdingPatternRoute
  '/shareholding-pattern-dec-2016': typeof ShareholdingPatternDec2016Route
  '/shareholding-pattern-dec-2020': typeof ShareholdingPatternDec2020Route
  '/shareholding-pattern-dec-2021': typeof ShareholdingPatternDec2021Route
  '/shareholding-pattern-dec-2022': typeof ShareholdingPatternDec2022Route
  '/shareholding-pattern-dec-2024': typeof ShareholdingPatternDec2024Route
  '/shareholding-pattern-dec-2025': typeof ShareholdingPatternDec2025Route
  '/shareholding-pattern-june-2021': typeof ShareholdingPatternJune2021Route
  '/shareholding-pattern-june-2023': typeof ShareholdingPatternJune2023Route
  '/shareholding-pattern-june-2024': typeof ShareholdingPatternJune2024Route
  '/shareholding-pattern-june-2025': typeof ShareholdingPatternJune2025Route
  '/shareholding-pattern-mar-2021': typeof ShareholdingPatternMar2021Route
  '/shareholding-pattern-mar-2022': typeof ShareholdingPatternMar2022Route
  '/shareholding-pattern-mar-2023': typeof ShareholdingPatternMar2023Route
  '/shareholding-pattern-mar-2025': typeof ShareholdingPatternMar2025Route
  '/shareholding-pattern-mar-2026': typeof ShareholdingPatternMar2026Route
  '/shareholding-pattern-march-2017': typeof ShareholdingPatternMarch2017Route
  '/shareholding-pattern-sep-2020': typeof ShareholdingPatternSep2020Route
  '/shareholding-pattern-sep-2021': typeof ShareholdingPatternSep2021Route
  '/shareholding-pattern-sep-2022': typeof ShareholdingPatternSep2022Route
  '/shareholding-pattern-sep-2023': typeof ShareholdingPatternSep2023Route
  '/shareholding-pattern-sep-2025': typeof ShareholdingPatternSep2025Route
  '/shareholding-pattern-sept-2016': typeof ShareholdingPatternSept2016Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/agm-results': typeof AgmResultsRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/annual-returns': typeof AnnualReturnsRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/contact': typeof ContactRoute
  '/financial-results': typeof FinancialResultsRoute
  '/forms': typeof FormsRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/newspaper-publications': typeof NewspaperPublicationsRoute
  '/policies': typeof PoliciesRoute
  '/rsca-reports': typeof RscaReportsRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
  '/shareholding-pattern': typeof ShareholdingPatternRoute
  '/shareholding-pattern-dec-2016': typeof ShareholdingPatternDec2016Route
  '/shareholding-pattern-dec-2020': typeof ShareholdingPatternDec2020Route
  '/shareholding-pattern-dec-2021': typeof ShareholdingPatternDec2021Route
  '/shareholding-pattern-dec-2022': typeof ShareholdingPatternDec2022Route
  '/shareholding-pattern-dec-2024': typeof ShareholdingPatternDec2024Route
  '/shareholding-pattern-dec-2025': typeof ShareholdingPatternDec2025Route
  '/shareholding-pattern-june-2021': typeof ShareholdingPatternJune2021Route
  '/shareholding-pattern-june-2023': typeof ShareholdingPatternJune2023Route
  '/shareholding-pattern-june-2024': typeof ShareholdingPatternJune2024Route
  '/shareholding-pattern-june-2025': typeof ShareholdingPatternJune2025Route
  '/shareholding-pattern-mar-2021': typeof ShareholdingPatternMar2021Route
  '/shareholding-pattern-mar-2022': typeof ShareholdingPatternMar2022Route
  '/shareholding-pattern-mar-2023': typeof ShareholdingPatternMar2023Route
  '/shareholding-pattern-mar-2025': typeof ShareholdingPatternMar2025Route
  '/shareholding-pattern-mar-2026': typeof ShareholdingPatternMar2026Route
  '/shareholding-pattern-march-2017': typeof ShareholdingPatternMarch2017Route
  '/shareholding-pattern-sep-2020': typeof ShareholdingPatternSep2020Route
  '/shareholding-pattern-sep-2021': typeof ShareholdingPatternSep2021Route
  '/shareholding-pattern-sep-2022': typeof ShareholdingPatternSep2022Route
  '/shareholding-pattern-sep-2023': typeof ShareholdingPatternSep2023Route
  '/shareholding-pattern-sep-2025': typeof ShareholdingPatternSep2025Route
  '/shareholding-pattern-sept-2016': typeof ShareholdingPatternSept2016Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agm-notices': typeof AgmNoticesRoute
  '/agm-results': typeof AgmResultsRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/annual-returns': typeof AnnualReturnsRoute
  '/board-meetings-notices': typeof BoardMeetingsNoticesRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/compliance-officer': typeof ComplianceOfficerRoute
  '/contact': typeof ContactRoute
  '/financial-results': typeof FinancialResultsRoute
  '/forms': typeof FormsRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/key-management-personnel': typeof KeyManagementPersonnelRoute
  '/newspaper-publications': typeof NewspaperPublicationsRoute
  '/policies': typeof PoliciesRoute
  '/rsca-reports': typeof RscaReportsRoute
  '/scrutinizers-report': typeof ScrutinizersReportRoute
  '/share-transfer-agent': typeof ShareTransferAgentRoute
  '/shareholding-pattern': typeof ShareholdingPatternRoute
  '/shareholding-pattern-dec-2016': typeof ShareholdingPatternDec2016Route
  '/shareholding-pattern-dec-2020': typeof ShareholdingPatternDec2020Route
  '/shareholding-pattern-dec-2021': typeof ShareholdingPatternDec2021Route
  '/shareholding-pattern-dec-2022': typeof ShareholdingPatternDec2022Route
  '/shareholding-pattern-dec-2024': typeof ShareholdingPatternDec2024Route
  '/shareholding-pattern-dec-2025': typeof ShareholdingPatternDec2025Route
  '/shareholding-pattern-june-2021': typeof ShareholdingPatternJune2021Route
  '/shareholding-pattern-june-2023': typeof ShareholdingPatternJune2023Route
  '/shareholding-pattern-june-2024': typeof ShareholdingPatternJune2024Route
  '/shareholding-pattern-june-2025': typeof ShareholdingPatternJune2025Route
  '/shareholding-pattern-mar-2021': typeof ShareholdingPatternMar2021Route
  '/shareholding-pattern-mar-2022': typeof ShareholdingPatternMar2022Route
  '/shareholding-pattern-mar-2023': typeof ShareholdingPatternMar2023Route
  '/shareholding-pattern-mar-2025': typeof ShareholdingPatternMar2025Route
  '/shareholding-pattern-mar-2026': typeof ShareholdingPatternMar2026Route
  '/shareholding-pattern-march-2017': typeof ShareholdingPatternMarch2017Route
  '/shareholding-pattern-sep-2020': typeof ShareholdingPatternSep2020Route
  '/shareholding-pattern-sep-2021': typeof ShareholdingPatternSep2021Route
  '/shareholding-pattern-sep-2022': typeof ShareholdingPatternSep2022Route
  '/shareholding-pattern-sep-2023': typeof ShareholdingPatternSep2023Route
  '/shareholding-pattern-sep-2025': typeof ShareholdingPatternSep2025Route
  '/shareholding-pattern-sept-2016': typeof ShareholdingPatternSept2016Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agm-notices'
    | '/agm-results'
    | '/annual-reports'
    | '/annual-returns'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/contact'
    | '/financial-results'
    | '/forms'
    | '/investor-grievance'
    | '/key-management-personnel'
    | '/newspaper-publications'
    | '/policies'
    | '/rsca-reports'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
    | '/shareholding-pattern'
    | '/shareholding-pattern-dec-2016'
    | '/shareholding-pattern-dec-2020'
    | '/shareholding-pattern-dec-2021'
    | '/shareholding-pattern-dec-2022'
    | '/shareholding-pattern-dec-2024'
    | '/shareholding-pattern-dec-2025'
    | '/shareholding-pattern-june-2021'
    | '/shareholding-pattern-june-2023'
    | '/shareholding-pattern-june-2024'
    | '/shareholding-pattern-june-2025'
    | '/shareholding-pattern-mar-2021'
    | '/shareholding-pattern-mar-2022'
    | '/shareholding-pattern-mar-2023'
    | '/shareholding-pattern-mar-2025'
    | '/shareholding-pattern-mar-2026'
    | '/shareholding-pattern-march-2017'
    | '/shareholding-pattern-sep-2020'
    | '/shareholding-pattern-sep-2021'
    | '/shareholding-pattern-sep-2022'
    | '/shareholding-pattern-sep-2023'
    | '/shareholding-pattern-sep-2025'
    | '/shareholding-pattern-sept-2016'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agm-notices'
    | '/agm-results'
    | '/annual-reports'
    | '/annual-returns'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/contact'
    | '/financial-results'
    | '/forms'
    | '/investor-grievance'
    | '/key-management-personnel'
    | '/newspaper-publications'
    | '/policies'
    | '/rsca-reports'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
    | '/shareholding-pattern'
    | '/shareholding-pattern-dec-2016'
    | '/shareholding-pattern-dec-2020'
    | '/shareholding-pattern-dec-2021'
    | '/shareholding-pattern-dec-2022'
    | '/shareholding-pattern-dec-2024'
    | '/shareholding-pattern-dec-2025'
    | '/shareholding-pattern-june-2021'
    | '/shareholding-pattern-june-2023'
    | '/shareholding-pattern-june-2024'
    | '/shareholding-pattern-june-2025'
    | '/shareholding-pattern-mar-2021'
    | '/shareholding-pattern-mar-2022'
    | '/shareholding-pattern-mar-2023'
    | '/shareholding-pattern-mar-2025'
    | '/shareholding-pattern-mar-2026'
    | '/shareholding-pattern-march-2017'
    | '/shareholding-pattern-sep-2020'
    | '/shareholding-pattern-sep-2021'
    | '/shareholding-pattern-sep-2022'
    | '/shareholding-pattern-sep-2023'
    | '/shareholding-pattern-sep-2025'
    | '/shareholding-pattern-sept-2016'
  id:
    | '__root__'
    | '/'
    | '/agm-notices'
    | '/agm-results'
    | '/annual-reports'
    | '/annual-returns'
    | '/board-meetings-notices'
    | '/board-of-directors'
    | '/compliance-officer'
    | '/contact'
    | '/financial-results'
    | '/forms'
    | '/investor-grievance'
    | '/key-management-personnel'
    | '/newspaper-publications'
    | '/policies'
    | '/rsca-reports'
    | '/scrutinizers-report'
    | '/share-transfer-agent'
    | '/shareholding-pattern'
    | '/shareholding-pattern-dec-2016'
    | '/shareholding-pattern-dec-2020'
    | '/shareholding-pattern-dec-2021'
    | '/shareholding-pattern-dec-2022'
    | '/shareholding-pattern-dec-2024'
    | '/shareholding-pattern-dec-2025'
    | '/shareholding-pattern-june-2021'
    | '/shareholding-pattern-june-2023'
    | '/shareholding-pattern-june-2024'
    | '/shareholding-pattern-june-2025'
    | '/shareholding-pattern-mar-2021'
    | '/shareholding-pattern-mar-2022'
    | '/shareholding-pattern-mar-2023'
    | '/shareholding-pattern-mar-2025'
    | '/shareholding-pattern-mar-2026'
    | '/shareholding-pattern-march-2017'
    | '/shareholding-pattern-sep-2020'
    | '/shareholding-pattern-sep-2021'
    | '/shareholding-pattern-sep-2022'
    | '/shareholding-pattern-sep-2023'
    | '/shareholding-pattern-sep-2025'
    | '/shareholding-pattern-sept-2016'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgmNoticesRoute: typeof AgmNoticesRoute
  AgmResultsRoute: typeof AgmResultsRoute
  AnnualReportsRoute: typeof AnnualReportsRoute
  AnnualReturnsRoute: typeof AnnualReturnsRoute
  BoardMeetingsNoticesRoute: typeof BoardMeetingsNoticesRoute
  BoardOfDirectorsRoute: typeof BoardOfDirectorsRoute
  ComplianceOfficerRoute: typeof ComplianceOfficerRoute
  ContactRoute: typeof ContactRoute
  FinancialResultsRoute: typeof FinancialResultsRoute
  FormsRoute: typeof FormsRoute
  InvestorGrievanceRoute: typeof InvestorGrievanceRoute
  KeyManagementPersonnelRoute: typeof KeyManagementPersonnelRoute
  NewspaperPublicationsRoute: typeof NewspaperPublicationsRoute
  PoliciesRoute: typeof PoliciesRoute
  RscaReportsRoute: typeof RscaReportsRoute
  ScrutinizersReportRoute: typeof ScrutinizersReportRoute
  ShareTransferAgentRoute: typeof ShareTransferAgentRoute
  ShareholdingPatternRoute: typeof ShareholdingPatternRoute
  ShareholdingPatternDec2016Route: typeof ShareholdingPatternDec2016Route
  ShareholdingPatternDec2020Route: typeof ShareholdingPatternDec2020Route
  ShareholdingPatternDec2021Route: typeof ShareholdingPatternDec2021Route
  ShareholdingPatternDec2022Route: typeof ShareholdingPatternDec2022Route
  ShareholdingPatternDec2024Route: typeof ShareholdingPatternDec2024Route
  ShareholdingPatternDec2025Route: typeof ShareholdingPatternDec2025Route
  ShareholdingPatternJune2021Route: typeof ShareholdingPatternJune2021Route
  ShareholdingPatternJune2023Route: typeof ShareholdingPatternJune2023Route
  ShareholdingPatternJune2024Route: typeof ShareholdingPatternJune2024Route
  ShareholdingPatternJune2025Route: typeof ShareholdingPatternJune2025Route
  ShareholdingPatternMar2021Route: typeof ShareholdingPatternMar2021Route
  ShareholdingPatternMar2022Route: typeof ShareholdingPatternMar2022Route
  ShareholdingPatternMar2023Route: typeof ShareholdingPatternMar2023Route
  ShareholdingPatternMar2025Route: typeof ShareholdingPatternMar2025Route
  ShareholdingPatternMar2026Route: typeof ShareholdingPatternMar2026Route
  ShareholdingPatternMarch2017Route: typeof ShareholdingPatternMarch2017Route
  ShareholdingPatternSep2020Route: typeof ShareholdingPatternSep2020Route
  ShareholdingPatternSep2021Route: typeof ShareholdingPatternSep2021Route
  ShareholdingPatternSep2022Route: typeof ShareholdingPatternSep2022Route
  ShareholdingPatternSep2023Route: typeof ShareholdingPatternSep2023Route
  ShareholdingPatternSep2025Route: typeof ShareholdingPatternSep2025Route
  ShareholdingPatternSept2016Route: typeof ShareholdingPatternSept2016Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shareholding-pattern-sept-2016': {
      id: '/shareholding-pattern-sept-2016'
      path: '/shareholding-pattern-sept-2016'
      fullPath: '/shareholding-pattern-sept-2016'
      preLoaderRoute: typeof ShareholdingPatternSept2016RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-sep-2025': {
      id: '/shareholding-pattern-sep-2025'
      path: '/shareholding-pattern-sep-2025'
      fullPath: '/shareholding-pattern-sep-2025'
      preLoaderRoute: typeof ShareholdingPatternSep2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-sep-2023': {
      id: '/shareholding-pattern-sep-2023'
      path: '/shareholding-pattern-sep-2023'
      fullPath: '/shareholding-pattern-sep-2023'
      preLoaderRoute: typeof ShareholdingPatternSep2023RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-sep-2022': {
      id: '/shareholding-pattern-sep-2022'
      path: '/shareholding-pattern-sep-2022'
      fullPath: '/shareholding-pattern-sep-2022'
      preLoaderRoute: typeof ShareholdingPatternSep2022RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-sep-2021': {
      id: '/shareholding-pattern-sep-2021'
      path: '/shareholding-pattern-sep-2021'
      fullPath: '/shareholding-pattern-sep-2021'
      preLoaderRoute: typeof ShareholdingPatternSep2021RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-sep-2020': {
      id: '/shareholding-pattern-sep-2020'
      path: '/shareholding-pattern-sep-2020'
      fullPath: '/shareholding-pattern-sep-2020'
      preLoaderRoute: typeof ShareholdingPatternSep2020RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-march-2017': {
      id: '/shareholding-pattern-march-2017'
      path: '/shareholding-pattern-march-2017'
      fullPath: '/shareholding-pattern-march-2017'
      preLoaderRoute: typeof ShareholdingPatternMarch2017RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-mar-2026': {
      id: '/shareholding-pattern-mar-2026'
      path: '/shareholding-pattern-mar-2026'
      fullPath: '/shareholding-pattern-mar-2026'
      preLoaderRoute: typeof ShareholdingPatternMar2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-mar-2025': {
      id: '/shareholding-pattern-mar-2025'
      path: '/shareholding-pattern-mar-2025'
      fullPath: '/shareholding-pattern-mar-2025'
      preLoaderRoute: typeof ShareholdingPatternMar2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-mar-2023': {
      id: '/shareholding-pattern-mar-2023'
      path: '/shareholding-pattern-mar-2023'
      fullPath: '/shareholding-pattern-mar-2023'
      preLoaderRoute: typeof ShareholdingPatternMar2023RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-mar-2022': {
      id: '/shareholding-pattern-mar-2022'
      path: '/shareholding-pattern-mar-2022'
      fullPath: '/shareholding-pattern-mar-2022'
      preLoaderRoute: typeof ShareholdingPatternMar2022RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-mar-2021': {
      id: '/shareholding-pattern-mar-2021'
      path: '/shareholding-pattern-mar-2021'
      fullPath: '/shareholding-pattern-mar-2021'
      preLoaderRoute: typeof ShareholdingPatternMar2021RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-june-2025': {
      id: '/shareholding-pattern-june-2025'
      path: '/shareholding-pattern-june-2025'
      fullPath: '/shareholding-pattern-june-2025'
      preLoaderRoute: typeof ShareholdingPatternJune2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-june-2024': {
      id: '/shareholding-pattern-june-2024'
      path: '/shareholding-pattern-june-2024'
      fullPath: '/shareholding-pattern-june-2024'
      preLoaderRoute: typeof ShareholdingPatternJune2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-june-2023': {
      id: '/shareholding-pattern-june-2023'
      path: '/shareholding-pattern-june-2023'
      fullPath: '/shareholding-pattern-june-2023'
      preLoaderRoute: typeof ShareholdingPatternJune2023RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-june-2021': {
      id: '/shareholding-pattern-june-2021'
      path: '/shareholding-pattern-june-2021'
      fullPath: '/shareholding-pattern-june-2021'
      preLoaderRoute: typeof ShareholdingPatternJune2021RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2025': {
      id: '/shareholding-pattern-dec-2025'
      path: '/shareholding-pattern-dec-2025'
      fullPath: '/shareholding-pattern-dec-2025'
      preLoaderRoute: typeof ShareholdingPatternDec2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2024': {
      id: '/shareholding-pattern-dec-2024'
      path: '/shareholding-pattern-dec-2024'
      fullPath: '/shareholding-pattern-dec-2024'
      preLoaderRoute: typeof ShareholdingPatternDec2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2022': {
      id: '/shareholding-pattern-dec-2022'
      path: '/shareholding-pattern-dec-2022'
      fullPath: '/shareholding-pattern-dec-2022'
      preLoaderRoute: typeof ShareholdingPatternDec2022RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2021': {
      id: '/shareholding-pattern-dec-2021'
      path: '/shareholding-pattern-dec-2021'
      fullPath: '/shareholding-pattern-dec-2021'
      preLoaderRoute: typeof ShareholdingPatternDec2021RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2020': {
      id: '/shareholding-pattern-dec-2020'
      path: '/shareholding-pattern-dec-2020'
      fullPath: '/shareholding-pattern-dec-2020'
      preLoaderRoute: typeof ShareholdingPatternDec2020RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern-dec-2016': {
      id: '/shareholding-pattern-dec-2016'
      path: '/shareholding-pattern-dec-2016'
      fullPath: '/shareholding-pattern-dec-2016'
      preLoaderRoute: typeof ShareholdingPatternDec2016RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholding-pattern': {
      id: '/shareholding-pattern'
      path: '/shareholding-pattern'
      fullPath: '/shareholding-pattern'
      preLoaderRoute: typeof ShareholdingPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-transfer-agent': {
      id: '/share-transfer-agent'
      path: '/share-transfer-agent'
      fullPath: '/share-transfer-agent'
      preLoaderRoute: typeof ShareTransferAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrutinizers-report': {
      id: '/scrutinizers-report'
      path: '/scrutinizers-report'
      fullPath: '/scrutinizers-report'
      preLoaderRoute: typeof ScrutinizersReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsca-reports': {
      id: '/rsca-reports'
      path: '/rsca-reports'
      fullPath: '/rsca-reports'
      preLoaderRoute: typeof RscaReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newspaper-publications': {
      id: '/newspaper-publications'
      path: '/newspaper-publications'
      fullPath: '/newspaper-publications'
      preLoaderRoute: typeof NewspaperPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-management-personnel': {
      id: '/key-management-personnel'
      path: '/key-management-personnel'
      fullPath: '/key-management-personnel'
      preLoaderRoute: typeof KeyManagementPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-grievance': {
      id: '/investor-grievance'
      path: '/investor-grievance'
      fullPath: '/investor-grievance'
      preLoaderRoute: typeof InvestorGrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-results': {
      id: '/financial-results'
      path: '/financial-results'
      fullPath: '/financial-results'
      preLoaderRoute: typeof FinancialResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-officer': {
      id: '/compliance-officer'
      path: '/compliance-officer'
      fullPath: '/compliance-officer'
      preLoaderRoute: typeof ComplianceOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-of-directors': {
      id: '/board-of-directors'
      path: '/board-of-directors'
      fullPath: '/board-of-directors'
      preLoaderRoute: typeof BoardOfDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-meetings-notices': {
      id: '/board-meetings-notices'
      path: '/board-meetings-notices'
      fullPath: '/board-meetings-notices'
      preLoaderRoute: typeof BoardMeetingsNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-returns': {
      id: '/annual-returns'
      path: '/annual-returns'
      fullPath: '/annual-returns'
      preLoaderRoute: typeof AnnualReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-reports': {
      id: '/annual-reports'
      path: '/annual-reports'
      fullPath: '/annual-reports'
      preLoaderRoute: typeof AnnualReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agm-results': {
      id: '/agm-results'
      path: '/agm-results'
      fullPath: '/agm-results'
      preLoaderRoute: typeof AgmResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agm-notices': {
      id: '/agm-notices'
      path: '/agm-notices'
      fullPath: '/agm-notices'
      preLoaderRoute: typeof AgmNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgmNoticesRoute: AgmNoticesRoute,
  AgmResultsRoute: AgmResultsRoute,
  AnnualReportsRoute: AnnualReportsRoute,
  AnnualReturnsRoute: AnnualReturnsRoute,
  BoardMeetingsNoticesRoute: BoardMeetingsNoticesRoute,
  BoardOfDirectorsRoute: BoardOfDirectorsRoute,
  ComplianceOfficerRoute: ComplianceOfficerRoute,
  ContactRoute: ContactRoute,
  FinancialResultsRoute: FinancialResultsRoute,
  FormsRoute: FormsRoute,
  InvestorGrievanceRoute: InvestorGrievanceRoute,
  KeyManagementPersonnelRoute: KeyManagementPersonnelRoute,
  NewspaperPublicationsRoute: NewspaperPublicationsRoute,
  PoliciesRoute: PoliciesRoute,
  RscaReportsRoute: RscaReportsRoute,
  ScrutinizersReportRoute: ScrutinizersReportRoute,
  ShareTransferAgentRoute: ShareTransferAgentRoute,
  ShareholdingPatternRoute: ShareholdingPatternRoute,
  ShareholdingPatternDec2016Route: ShareholdingPatternDec2016Route,
  ShareholdingPatternDec2020Route: ShareholdingPatternDec2020Route,
  ShareholdingPatternDec2021Route: ShareholdingPatternDec2021Route,
  ShareholdingPatternDec2022Route: ShareholdingPatternDec2022Route,
  ShareholdingPatternDec2024Route: ShareholdingPatternDec2024Route,
  ShareholdingPatternDec2025Route: ShareholdingPatternDec2025Route,
  ShareholdingPatternJune2021Route: ShareholdingPatternJune2021Route,
  ShareholdingPatternJune2023Route: ShareholdingPatternJune2023Route,
  ShareholdingPatternJune2024Route: ShareholdingPatternJune2024Route,
  ShareholdingPatternJune2025Route: ShareholdingPatternJune2025Route,
  ShareholdingPatternMar2021Route: ShareholdingPatternMar2021Route,
  ShareholdingPatternMar2022Route: ShareholdingPatternMar2022Route,
  ShareholdingPatternMar2023Route: ShareholdingPatternMar2023Route,
  ShareholdingPatternMar2025Route: ShareholdingPatternMar2025Route,
  ShareholdingPatternMar2026Route: ShareholdingPatternMar2026Route,
  ShareholdingPatternMarch2017Route: ShareholdingPatternMarch2017Route,
  ShareholdingPatternSep2020Route: ShareholdingPatternSep2020Route,
  ShareholdingPatternSep2021Route: ShareholdingPatternSep2021Route,
  ShareholdingPatternSep2022Route: ShareholdingPatternSep2022Route,
  ShareholdingPatternSep2023Route: ShareholdingPatternSep2023Route,
  ShareholdingPatternSep2025Route: ShareholdingPatternSep2025Route,
  ShareholdingPatternSept2016Route: ShareholdingPatternSept2016Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
